#---------------------------#
#  AzureDevOps CI pipeline  #
#---------------------------#
trigger:
- master
- dev

variables:
  GIT_CONFIG_PARAMETERS: "'core.autocrlf=false'"
  POWERSHELL_TELEMETRY_OPTOUT: 1

pool:
  vmImage: 'VS2017-Win2016'

steps:
- powershell: |
    Get-ChildItem -Path env:
  displayName: Capture environment

- powershell: |
    Enable-PSRemoting -Force -SkipNetworkProfileCheck
    Start-Service winrm
  displayName: Start WinRM

- task: Pester@8
  displayName: Pester Unit Test
  inputs:
     scriptFolder: $(System.DefaultWorkingDirectory)\*
     resultsFile: $(System.DefaultWorkingDirectory)\Test-Pester.XML
     tag: Unit
     run32Bit: False
