
[ClassVersion("1.0.0.0"), FriendlyName("x7ZipArchive")]
class x7ZipArchive : OMI_BaseResource
{
    [Read] String Ensure;
    [Key] String Path;
    [key] String Destination;
    [Write] Boolean Validate;
    [Write, ValueMap{"ModifiedDate","Size","CRC32"}, Values{"ModifiedDate","Size","CRC32"}] String Checksum;
    [Write] Boolean IgnoreRoot;
    [Write] Boolean Clean;
    [Write, EmbeddedInstance("MSFT_Credential")] String Credential;
};

