name: 7ZipArchiveDsc

on: [push]

jobs:
  Tests_PS5:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
      - uses: actions/checkout@v2

      - name: Install Pester
        run: Install-Module Pester -MaximumVersion 4.10.1 -Force -AllowClobber -Scope CurrentUser -SkipPublisherCheck

      - name: Collect environment
        run: |
          $PSVersionTable
          Get-ChildItem 'env:' | Format-Table -AutoSize -Wrap
          Get-Module -ListAvailable

      - name: Configure WinRM
        run: winrm quickconfig -quiet

      - name: Tests
        run: Invoke-Pester -EnableExit
