name: 7ZipArchiveDsc

on: [push]

jobs:
  Tests_PowerShell_5:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
      - uses: actions/checkout@v4

      - name: Install Pester
        run: Install-Module Pester -MaximumVersion 4.10.1 -Force -AllowClobber -Scope CurrentUser -SkipPublisherCheck

      - name: Configure WinRM
        run: winrm quickconfig -quiet

      - name: Collect environment
        run: |
          $PSVersionTable
          Get-ChildItem 'env:' | Format-Table -AutoSize -Wrap

      - name: Unit Tests
        run: Invoke-Pester -Tag 'Unit' -EnableExit

      - name: Integration Tests
        run: Invoke-Pester -Tag 'Integration' -EnableExit

  Tests_PowerShell_7:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v4

      - name: Install Pester
        run: Install-Module Pester -MaximumVersion 4.10.1 -Force -AllowClobber -Scope CurrentUser -SkipPublisherCheck

      - name: Install PSDesiredStateConfiguration
        run: Install-Module PSDesiredStateConfiguration -Repository PSGallery -MaximumVersion 2.99 -Force -AllowClobber

      - name: Configure WinRM
        run: winrm quickconfig -quiet

      - name: Collect environment
        run: |
          $PSVersionTable
          Get-ChildItem 'env:' | Format-Table -AutoSize -Wrap
          Get-Module -ListAvailable

      - name: Unit Tests
        run: Invoke-Pester -Tag 'Unit' -EnableExit

      - name: Integration Tests
        run: Invoke-Pester -Tag 'Integration' -EnableExit
